version: '3'

services:
  
  demo-api:
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    ports:
      - 8000:8000 
    volumes:
      - ./backend/api:/src
    environment:
      - ENVIRON
  
  node:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd ./frontend/react-app && yarn start'
    ports:
      - '3000:3000'